### ISSUE TITLE
Updating the Xtext Community Website

### ISSUE THREAD

**Issue by miklossy** [xatkit-bot-platform/xatkit-eclipse#25]
Hello xatkit-eclipse team,

The Xtext team would like to update the [Xtext community website](https://www.eclipse.org/Xtext/community.html) listing all the cool projects people are building around Xtext/Xtend.

See also the corresponding [GitHub issue](https://github.com/eclipse/xtext/issues/1541) and [Bugzilla ticket](https://bugs.eclipse.org/bugs/show_bug.cgi?id=328477)

If you are interested that the xatkit-eclipse project is listed there, please provide the following information as a comment to this issue:

```
<tr>
	<td><a href="project_link">project_name</a></td>
	<td>project_description_max_2_sentences</td>
	<td>license</td>
	<td>category</td>
	<td>author(s)</td>
</tr>
```

We will then update the Xtext community website and get it online as soon as possible.

Thanks!
Tamás

**Comment by gdaniel** [comment]
Hi Tamás,

We'll be happy to be part of the Xtext community website! You'll find below the requested information. Note that I put the Xatkit project instead of xatkit-eclipse: all the Xatkit internals use Xtext to parse the models created with the editor.

```html
<tr>
	<td><a href="https://xatkit.com/">Xatkit</a></td>
	<td>Xatkit is a model-based bot development framework that provides a set of DSLs to specify the behavior, backend actions, and execution logic of your (chat) bot. Xatkit embeds an execution engine that manages the deployment and execution of the specified bot.</td>
	<td>EPL.v2</td>
	<td>Bot Development</td>
	<td>Jordi Cabot, Gwendal Daniel</td>
</tr>
```

Let me know if I need to post a comment on the issue you referenced.

Thanks

Gwendal

**Comment by miklossy** [comment]
Thank you Gwendal!

**Comment by miklossy** [comment]
The `Xatkit` project has been added to the [Xtext community website](https://www.eclipse.org/Xtext/community.html).
