### ISSUE TITLE
Ignore generation of the *.ide plugins 

### ISSUE THREAD

**Issue by nbhusare** [xatkit-bot-platform/xatkit-eclipse#29]
Xtext generates the *.ide project to host the platform (Eclipse) independent stuff - To support Language server protocol, Xtext on the web. Since xatkit has no plans to support these features, the generation of the project should be ignored.

**Comment by miklossy** [comment]
Since the *.ide projects has been integrated into the *.ui project with the commit https://github.com/xatkit-bot-platform/xatkit-eclipse/commit/2c6549588311060f7ef31fefee09b41f0039ca14 I think this issue can be closed.

**Comment by gdaniel** [comment]
Thanks for the reminder, closing it
